# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01a602c22ae7f55c28f66cc72ad955b81038aa511caf726821180de66914a4c0176f50032ecdf5461e03397ae30665c5d75da4a832b6c42460189a865b1aa5f

test:
  secret_key_base: 1a4582b90f21be85930f23304ae98b31ea0942439a9a367fc4244f9540a3aaeeccb441a922f8c2f3094b78a096e76ef79523582b666e7f58509410065cd364f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
